cc:
  datatype: H5
  data_path: ./data
  files_jug: single
  shape: 20*
  cc_len: 10
  time_len: 600
  c_range: 60
  dr: 10.0
  step: 20
  outputdir: ./output
  example_path: ./data/example.h5
  time_step: 10
  smooth_N: 10
  freqmin: 0.1
  freqmax: 30
  b_ch: 300
  e_ch: 1000
  freq_norm: rma
  substack: true
  meta_flag: false
  meta_file: /
  samplerate: 200
  samplerate_in_use: 100
  whole_array: false
  files_num: 4
  time_range: 5
  STA: false
disp:
  range:
  - 0
  - 900
  fmin: 0.01
  fmax: 8
  vmax: 1000
  vmin: 100
  dv: 5
  df: 0.1
  dt: 0.01
  cc_len: 10
  time_range: 10
  save_path: false
  dr: 10.0
  Part: causal
  c_range: 60
  method: Phaseshift
  step: 20
inv_para:
  lr: 0.14
  optimizer: Adam
  es: 1e-08
  step_size: 20
  gamma: 0.82
  iter_max: 100.0
  inv_object: vs
  max_mode: 3
  vsrange:
  - 0.9
  - 1.2
  inittal_method: Brocher
  init_model_depth: 60.0
  model_num: 100
  retry_bad_channel: true
  retry_nstart_factor: 1.8
  retry_vsrange_expand: 0.18
  retry_thickness_expand: 0.12
  ls: true
  device: cuda
  fmin: 0.01
  fmax: 8
  vmax: 1000
  vmin: 100
  step: 20
