# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow - inv.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.paramshow = QtWidgets.QTableWidget(self.centralwidget)
        self.paramshow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramshow.sizePolicy().hasHeightForWidth())
        self.paramshow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.paramshow.setFont(font)
        self.paramshow.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.paramshow.setMouseTracking(True)
        self.paramshow.setTabletTracking(True)
        self.paramshow.setAcceptDrops(True)
        self.paramshow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.paramshow.setAutoFillBackground(True)
        self.paramshow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.paramshow.setLineWidth(5)
        self.paramshow.setMidLineWidth(-3)
        self.paramshow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.paramshow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.paramshow.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.paramshow.setAutoScrollMargin(20)
        self.paramshow.setAlternatingRowColors(False)
        self.paramshow.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.paramshow.setShowGrid(True)
        self.paramshow.setColumnCount(2)
        self.paramshow.setObjectName("paramshow")
        self.paramshow.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow.setHorizontalHeaderItem(1, item)
        self.paramshow.horizontalHeader().setVisible(True)
        self.paramshow.horizontalHeader().setCascadingSectionResizes(False)
        self.paramshow.horizontalHeader().setDefaultSectionSize(140)
        self.paramshow.horizontalHeader().setHighlightSections(False)
        self.paramshow.horizontalHeader().setSortIndicatorShown(False)
        self.paramshow.horizontalHeader().setStretchLastSection(True)
        self.paramshow.verticalHeader().setVisible(True)
        self.paramshow.verticalHeader().setCascadingSectionResizes(True)
        self.paramshow.verticalHeader().setSortIndicatorShown(True)
        self.paramshow.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.paramshow)
        self.inv_para = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.inv_para.setFont(font)
        self.inv_para.setObjectName("inv_para")
        self.verticalLayout.addWidget(self.inv_para)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.paramshow_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.paramshow_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramshow_2.sizePolicy().hasHeightForWidth())
        self.paramshow_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.paramshow_2.setFont(font)
        self.paramshow_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.paramshow_2.setMouseTracking(True)
        self.paramshow_2.setTabletTracking(True)
        self.paramshow_2.setAcceptDrops(True)
        self.paramshow_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.paramshow_2.setAutoFillBackground(True)
        self.paramshow_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.paramshow_2.setLineWidth(5)
        self.paramshow_2.setMidLineWidth(-3)
        self.paramshow_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.paramshow_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.paramshow_2.setAutoScrollMargin(20)
        self.paramshow_2.setAlternatingRowColors(False)
        self.paramshow_2.setShowGrid(True)
        self.paramshow_2.setColumnCount(3)
        self.paramshow_2.setObjectName("paramshow_2")
        self.paramshow_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow_2.setHorizontalHeaderItem(2, item)
        self.paramshow_2.horizontalHeader().setVisible(True)
        self.paramshow_2.horizontalHeader().setCascadingSectionResizes(False)
        self.paramshow_2.horizontalHeader().setDefaultSectionSize(140)
        self.paramshow_2.horizontalHeader().setHighlightSections(False)
        self.paramshow_2.horizontalHeader().setSortIndicatorShown(False)
        self.paramshow_2.horizontalHeader().setStretchLastSection(True)
        self.paramshow_2.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.paramshow_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.removel = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.removel.setFont(font)
        self.removel.setObjectName("removel")
        self.verticalLayout.addWidget(self.removel)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dispbar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispbar.sizePolicy().hasHeightForWidth())
        self.dispbar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dispbar.setFont(font)
        self.dispbar.setProperty("value", 0)
        self.dispbar.setObjectName("dispbar")
        self.horizontalLayout.addWidget(self.dispbar)
        self.runinv = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.runinv.setFont(font)
        self.runinv.setObjectName("runinv")
        self.horizontalLayout.addWidget(self.runinv)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.picchose_disp = QtWidgets.QLineEdit(self.centralwidget)
        self.picchose_disp.setBaseSize(QtCore.QSize(400, 22))

        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setItalic(True)
        self.picchose_disp.setFont(font)
        self.picchose_disp.setAcceptDrops(False)
        self.picchose_disp.setObjectName("picchose_disp")
        self.horizontalLayout_2.addWidget(self.picchose_disp)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loadp = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.loadp.setFont(font)
        self.loadp.setObjectName("loadp")
        self.horizontalLayout_4.addWidget(self.loadp)
        self.plotp = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.plotp.setFont(font)
        self.plotp.setObjectName("plotp")
        self.horizontalLayout_4.addWidget(self.plotp)
        self.savep = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.savep.setFont(font)
        self.savep.setObjectName("savep")
        self.horizontalLayout_4.addWidget(self.savep)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 20))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "inv paras"))
        self.paramshow.setSortingEnabled(False)
        item = self.paramshow.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "KEY"))
        item = self.paramshow.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALUE"))
        self.inv_para.setText(_translate("MainWindow", "load"))
        self.label_3.setText(_translate("MainWindow", "init model range"))
        self.paramshow_2.setSortingEnabled(False)
        item = self.paramshow_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "D"))
        item = self.paramshow_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vs"))
        item = self.paramshow_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "density"))
        self.removel.setText(_translate("MainWindow", "remove layer"))
        self.pushButton.setText(_translate("MainWindow", "add layer"))
        self.runinv.setText(_translate("MainWindow", "run inversion"))
        self.label_5.setText(_translate("MainWindow", "Disp_Inv_Process"))
        self.label_6.setText(_translate("MainWindow", "Vel_Inv_Process"))
        self.label_7.setText(_translate("MainWindow", "Vs Profile"))
        self.loadp.setText(_translate("MainWindow", "load"))
        self.plotp.setText(_translate("MainWindow", "plot"))
        self.savep.setText(_translate("MainWindow", "save"))
        self.menufile.setTitle(_translate("MainWindow", "file"))

import backgrand_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

