# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow - test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1745, 1029)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 900))
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.parampath = QtWidgets.QLineEdit(self.centralwidget)
        self.parampath.setObjectName("parampath")
        self.verticalLayout.addWidget(self.parampath)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.paramsload = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsload.sizePolicy().hasHeightForWidth())
        self.paramsload.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.paramsload.setFont(font)
        self.paramsload.setObjectName("paramsload")
        self.horizontalLayout.addWidget(self.paramsload)
        self.ccrun = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccrun.sizePolicy().hasHeightForWidth())
        self.ccrun.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ccrun.setFont(font)
        self.ccrun.setObjectName("ccrun")
        self.horizontalLayout.addWidget(self.ccrun)
        self.ccstop = QtWidgets.QPushButton(self.centralwidget)
        self.ccstop.setObjectName("ccstop")
        self.horizontalLayout.addWidget(self.ccstop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.paramshow = QtWidgets.QTableWidget(self.centralwidget)
        self.paramshow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramshow.sizePolicy().hasHeightForWidth())
        self.paramshow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.paramshow.setFont(font)
        self.paramshow.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.paramshow.setMouseTracking(True)
        self.paramshow.setTabletTracking(True)
        self.paramshow.setAcceptDrops(True)
        self.paramshow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.paramshow.setAutoFillBackground(True)
        self.paramshow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.paramshow.setLineWidth(5)
        self.paramshow.setMidLineWidth(-3)
        self.paramshow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.paramshow.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.paramshow.setAutoScrollMargin(20)
        self.paramshow.setAlternatingRowColors(False)
        self.paramshow.setShowGrid(True)
        self.paramshow.setColumnCount(2)
        self.paramshow.setObjectName("paramshow")
        self.paramshow.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow.setHorizontalHeaderItem(1, item)
        self.paramshow.horizontalHeader().setVisible(True)
        self.paramshow.horizontalHeader().setCascadingSectionResizes(False)
        self.paramshow.horizontalHeader().setDefaultSectionSize(140)
        self.paramshow.horizontalHeader().setHighlightSections(False)
        self.paramshow.horizontalHeader().setSortIndicatorShown(False)
        self.paramshow.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.paramshow)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.savecc = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.savecc.setFont(font)
        self.savecc.setObjectName("savecc")
        self.horizontalLayout_10.addWidget(self.savecc)
        self.plotbut = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotbut.sizePolicy().hasHeightForWidth())
        self.plotbut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.plotbut.setFont(font)
        self.plotbut.setObjectName("plotbut")
        self.horizontalLayout_10.addWidget(self.plotbut)
        self.picchose = QtWidgets.QLineEdit(self.centralwidget)
        self.picchose.setBaseSize(QtCore.QSize(400, 22))
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setItalic(True)
        self.picchose.setFont(font)
        self.picchose.setAcceptDrops(False)
        self.picchose.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.picchose.setObjectName("picchose")
        self.horizontalLayout_10.addWidget(self.picchose)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.last_cc = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_cc.sizePolicy().hasHeightForWidth())
        self.last_cc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.last_cc.setFont(font)
        self.last_cc.setObjectName("last_cc")
        self.horizontalLayout_2.addWidget(self.last_cc)
        self.next_cc = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_cc.sizePolicy().hasHeightForWidth())
        self.next_cc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.next_cc.setFont(font)
        self.next_cc.setObjectName("next_cc")
        self.horizontalLayout_2.addWidget(self.next_cc)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.dataproperties = QtWidgets.QTableWidget(self.centralwidget)
        self.dataproperties.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataproperties.sizePolicy().hasHeightForWidth())
        self.dataproperties.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dataproperties.setFont(font)
        self.dataproperties.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dataproperties.setMouseTracking(True)
        self.dataproperties.setTabletTracking(True)
        self.dataproperties.setAcceptDrops(True)
        self.dataproperties.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dataproperties.setAutoFillBackground(True)
        self.dataproperties.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataproperties.setLineWidth(5)
        self.dataproperties.setMidLineWidth(-3)
        self.dataproperties.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.dataproperties.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.dataproperties.setAutoScrollMargin(20)
        self.dataproperties.setObjectName("dataproperties")
        self.dataproperties.setColumnCount(2)
        self.dataproperties.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dataproperties.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataproperties.setHorizontalHeaderItem(1, item)
        self.dataproperties.horizontalHeader().setCascadingSectionResizes(False)
        self.dataproperties.horizontalHeader().setDefaultSectionSize(140)
        self.dataproperties.horizontalHeader().setHighlightSections(False)
        self.dataproperties.horizontalHeader().setSortIndicatorShown(False)
        self.dataproperties.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.dataproperties)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.messgeshow = QtWidgets.QLineEdit(self.centralwidget)
        self.messgeshow.setBaseSize(QtCore.QSize(400, 22))
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setItalic(True)
        self.messgeshow.setFont(font)
        self.messgeshow.setAcceptDrops(False)
        self.messgeshow.setObjectName("messgeshow")
        self.verticalLayout_4.addWidget(self.messgeshow)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ccbar = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ccbar.setFont(font)
        self.ccbar.setProperty("value", 0)
        self.ccbar.setOrientation(QtCore.Qt.Horizontal)
        self.ccbar.setObjectName("ccbar")
        self.horizontalLayout_6.addWidget(self.ccbar)
        self.cut_save = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cut_save.setFont(font)
        self.cut_save.setObjectName("cut_save")
        self.horizontalLayout_6.addWidget(self.cut_save)
        self.horizontalLayout_6.setStretch(0, 8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.save_disp = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.save_disp.setFont(font)
        self.save_disp.setObjectName("save_disp")
        self.horizontalLayout_8.addWidget(self.save_disp)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.last_disp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_disp.sizePolicy().hasHeightForWidth())
        self.last_disp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.last_disp.setFont(font)
        self.last_disp.setObjectName("last_disp")
        self.horizontalLayout_7.addWidget(self.last_disp)
        self.picchose_disp = QtWidgets.QLineEdit(self.centralwidget)
        self.picchose_disp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picchose_disp.sizePolicy().hasHeightForWidth())
        self.picchose_disp.setSizePolicy(sizePolicy)
        self.picchose_disp.setBaseSize(QtCore.QSize(400, 22))
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setItalic(True)
        self.picchose_disp.setFont(font)
        self.picchose_disp.setAcceptDrops(False)
        self.picchose_disp.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.picchose_disp.setObjectName("picchose_disp")
        self.horizontalLayout_7.addWidget(self.picchose_disp)
        self.next_disp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_disp.sizePolicy().hasHeightForWidth())
        self.next_disp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.next_disp.setFont(font)
        self.next_disp.setAutoDefault(False)
        self.next_disp.setObjectName("next_disp")
        self.horizontalLayout_7.addWidget(self.next_disp)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.dispbar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispbar.sizePolicy().hasHeightForWidth())
        self.dispbar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dispbar.setFont(font)
        self.dispbar.setProperty("value", 0)
        self.dispbar.setObjectName("dispbar")
        self.horizontalLayout_11.addWidget(self.dispbar)
        self.savedisp = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.savedisp.setFont(font)
        self.savedisp.setObjectName("savedisp")
        self.horizontalLayout_11.addWidget(self.savedisp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(20)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.sen_pick = QtWidgets.QLineEdit(self.centralwidget)
        self.sen_pick.setObjectName("sen_pick")
        self.horizontalLayout_12.addWidget(self.sen_pick)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_12.addWidget(self.pushButton)
        self.ccrun_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccrun_2.sizePolicy().hasHeightForWidth())
        self.ccrun_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ccrun_2.setFont(font)
        self.ccrun_2.setObjectName("ccrun_2")
        self.horizontalLayout_12.addWidget(self.ccrun_2)
        self.horizontalLayout_12.setStretch(0, 2)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(2, 1)
        self.horizontalLayout_12.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.paramshow_disp = QtWidgets.QTableWidget(self.centralwidget)
        self.paramshow_disp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramshow_disp.sizePolicy().hasHeightForWidth())
        self.paramshow_disp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.paramshow_disp.setFont(font)
        self.paramshow_disp.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.paramshow_disp.setMouseTracking(True)
        self.paramshow_disp.setTabletTracking(True)
        self.paramshow_disp.setAcceptDrops(True)
        self.paramshow_disp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.paramshow_disp.setAutoFillBackground(False)
        self.paramshow_disp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.paramshow_disp.setLineWidth(5)
        self.paramshow_disp.setMidLineWidth(-3)
        self.paramshow_disp.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.paramshow_disp.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.paramshow_disp.setAutoScrollMargin(20)
        self.paramshow_disp.setAlternatingRowColors(False)
        self.paramshow_disp.setShowGrid(True)
        self.paramshow_disp.setColumnCount(2)
        self.paramshow_disp.setObjectName("paramshow_disp")
        self.paramshow_disp.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow_disp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.paramshow_disp.setHorizontalHeaderItem(1, item)
        self.paramshow_disp.horizontalHeader().setVisible(True)
        self.paramshow_disp.horizontalHeader().setCascadingSectionResizes(False)
        self.paramshow_disp.horizontalHeader().setDefaultSectionSize(128)
        self.paramshow_disp.horizontalHeader().setHighlightSections(False)
        self.paramshow_disp.horizontalHeader().setSortIndicatorShown(False)
        self.paramshow_disp.verticalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.paramshow_disp)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.paramloaddisp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramloaddisp.sizePolicy().hasHeightForWidth())
        self.paramloaddisp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.paramloaddisp.setFont(font)
        self.paramloaddisp.setObjectName("paramloaddisp")
        self.horizontalLayout_3.addWidget(self.paramloaddisp)
        self.dispload = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispload.sizePolicy().hasHeightForWidth())
        self.dispload.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dispload.setFont(font)
        self.dispload.setObjectName("dispload")
        self.horizontalLayout_3.addWidget(self.dispload)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ccload = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccload.sizePolicy().hasHeightForWidth())
        self.ccload.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ccload.setFont(font)
        self.ccload.setObjectName("ccload")
        self.horizontalLayout_4.addWidget(self.ccload)
        self.rundisp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rundisp.sizePolicy().hasHeightForWidth())
        self.rundisp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.rundisp.setFont(font)
        self.rundisp.setObjectName("rundisp")
        self.horizontalLayout_4.addWidget(self.rundisp)
        self.plotdisp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotdisp.sizePolicy().hasHeightForWidth())
        self.plotdisp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.plotdisp.setFont(font)
        self.plotdisp.setObjectName("plotdisp")
        self.horizontalLayout_4.addWidget(self.plotdisp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pick = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pick.setFont(font)
        self.pick.setObjectName("pick")
        self.horizontalLayout_5.addWidget(self.pick)
        self.inv_para = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.inv_para.setFont(font)
        self.inv_para.setObjectName("inv_para")
        self.horizontalLayout_5.addWidget(self.inv_para)
        self.plotinv = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.plotinv.setFont(font)
        self.plotinv.setObjectName("plotinv")
        self.horizontalLayout_5.addWidget(self.plotinv)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1745, 22))
        self.menubar.setObjectName("menubar")
        self.menuFILE = QtWidgets.QMenu(self.menubar)
        self.menuFILE.setObjectName("menuFILE")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.menuFILE.addAction(self.action)
        self.menubar.addAction(self.menuFILE.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Params File Path(yaml)"))
        self.pushButton_3.setText(_translate("MainWindow", "Browse"))
        self.paramsload.setText(_translate("MainWindow", "Paraload"))
        self.ccrun.setText(_translate("MainWindow", "Run CC"))
        self.ccstop.setText(_translate("MainWindow", "Stop CC"))
        self.paramshow.setSortingEnabled(False)
        item = self.paramshow.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "KEY"))
        item = self.paramshow.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALUE"))
        self.savecc.setText(_translate("MainWindow", "Save cc files"))
        self.plotbut.setText(_translate("MainWindow", "Plot"))
        self.label_2.setText(_translate("MainWindow", "Data Properties"))
        self.last_cc.setText(_translate("MainWindow", "last"))
        self.next_cc.setText(_translate("MainWindow", "next"))
        item = self.dataproperties.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PROPERTIES"))
        item = self.dataproperties.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALUE"))
        self.cut_save.setText(_translate("MainWindow", "CUT"))
        self.label_5.setText(_translate("MainWindow", "Disp Show"))
        self.save_disp.setText(_translate("MainWindow", "Save disp"))
        self.last_disp.setText(_translate("MainWindow", "last"))
        self.next_disp.setText(_translate("MainWindow", "next"))
        self.savedisp.setText(_translate("MainWindow", "save"))
        self.label_6.setText(_translate("MainWindow", "Free Show"))
        self.pushButton.setText(_translate("MainWindow", "Sen-kernels"))
        self.ccrun_2.setText(_translate("MainWindow", "FK"))
        self.label_3.setText(_translate("MainWindow", "Disp Params"))
        self.paramshow_disp.setSortingEnabled(False)
        item = self.paramshow_disp.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "KEY"))
        item = self.paramshow_disp.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALUE"))
        self.paramloaddisp.setText(_translate("MainWindow", "Para load"))
        self.dispload.setText(_translate("MainWindow", "disp_load"))
        self.ccload.setText(_translate("MainWindow", "cc_load"))
        self.rundisp.setText(_translate("MainWindow", "Run DISP"))
        self.plotdisp.setText(_translate("MainWindow", "PlotDISP"))
        self.pick.setText(_translate("MainWindow", "pick_ML"))
        self.inv_para.setText(_translate("MainWindow", "inv"))
        self.plotinv.setText(_translate("MainWindow", "Plot Inv"))
        self.label_4.setText(_translate("MainWindow", "Running text"))
        self.menuFILE.setTitle(_translate("MainWindow", "file"))
        self.action.setText(_translate("MainWindow", "save"))

import backgrand_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

