# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow - PICK.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 383)
        # MainWindow.setStyleSheet("""
        #      QMainWindow {
        #          background-image: url(":/jpeg/微信图片_20250307171720.png");
        #      }
        #  """)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dispshow = QtWidgets.QGraphicsView(self.centralwidget)
        self.dispshow.setObjectName("dispshow")
        self.verticalLayout.addWidget(self.dispshow)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.last_disp = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.last_disp.setFont(font)
        self.last_disp.setObjectName("last_disp")
        self.horizontalLayout.addWidget(self.last_disp)
        self.picchose_disp = QtWidgets.QLineEdit(self.centralwidget)
        self.picchose_disp.setBaseSize(QtCore.QSize(400, 22))
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setItalic(True)
        self.picchose_disp.setFont(font)
        self.picchose_disp.setAcceptDrops(False)
        self.picchose_disp.setObjectName("picchose_disp")
        self.horizontalLayout.addWidget(self.picchose_disp)
        self.next_disp = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.next_disp.setFont(font)
        self.next_disp.setObjectName("next_disp")
        self.horizontalLayout.addWidget(self.next_disp)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.parampath = QtWidgets.QLineEdit(self.centralwidget)
        self.parampath.setObjectName("parampath")
        self.verticalLayout_2.addWidget(self.parampath)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.paramsload = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsload.sizePolicy().hasHeightForWidth())
        self.paramsload.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.paramsload.setFont(font)
        self.paramsload.setObjectName("paramsload")
        self.horizontalLayout_2.addWidget(self.paramsload)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plotdisp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotdisp.sizePolicy().hasHeightForWidth())
        self.plotdisp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.plotdisp.setFont(font)
        self.plotdisp.setObjectName("plotdisp")
        self.horizontalLayout_3.addWidget(self.plotdisp)
        self.pick_but = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("P052 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pick_but.setFont(font)
        self.pick_but.setObjectName("pick_but")
        self.horizontalLayout_3.addWidget(self.pick_but)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.dispshow_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.dispshow_2.setObjectName("dispshow_2")
        self.verticalLayout_2.addWidget(self.dispshow_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 20))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.last_disp.setText(_translate("MainWindow", "last"))
        self.next_disp.setText(_translate("MainWindow", "next"))
        self.pushButton_3.setText(_translate("MainWindow", "Browse"))
        self.paramsload.setText(_translate("MainWindow", "Model Load"))
        self.plotdisp.setText(_translate("MainWindow", "PlotDISP"))
        self.pick_but.setText(_translate("MainWindow", "PICK"))
        self.menufile.setTitle(_translate("MainWindow", "file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

